---
version: 1
environment: local
health_check:
  enabled: false
  port: 1234
  interface: 0.0.0.0
  debug_envs:
    - local
monitoring:
  enabled: false
  disabled_metrics: []
masking_fields:
  - token
  - access_token
  - refresh_token
  - epkId
  - profileId
user_save_collisions_tries: 2
self_service_with_state_save_messages: true
project_id: template-app-id
<<<<<<< HEAD
consumer_topic: "app"
=======
max_concurrent_messages: 1
>>>>>>> eca49afd6e869eeaa3c571c557c6ec5254dd3757
